### ISSUE TITLE
Switch from blas-sys to blas crate

### ISSUE THREAD

**Issue by gustav1101** [vab9/pir-project2017#14]
As discussed in #13 we should switch to [this blas crate](https://crates.io/crates/blas). The transition should not be too hard (especially since we didn't really use it yet), only the parameter types need to be adjusted.

Need to update the wiki and our example (probably @toschneider will have to do that), then this issue can be closed, wrote it mainly for visibility.

**Comment by toschneider** [comment]
the example is now using blas

**Comment by gustav1101** [comment]
Wikipage is updated as well.
