### ISSUE TITLE
Find suitable library for fast algebra

### ISSUE THREAD

**Issue by gustav1101** [vab9/pir-project2017#2]
Maybe something that implements BLAS. Don't know yet what we will need exactly.

**Comment by joarndt** [comment]
blas-sys is  a BLAS implementation in Rust that uses cblas.
blas-sys isn't documented properly so i will link the cblas documentation.
https://software.intel.com/en-us/node/520730 //documentation of cblas
https://crates.io/crates/blas-sys                       //link to the crate
needs probably build-essential and gfortran packages installed

**Comment by gustav1101** [comment]
Will close this for now. If it turns out to be nothing we can use I'll reopen it.
