### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by joarndt** [vab9/pir-project2017#25]
Implement easy logging for our Project and put usefull logs in our Project.

**Comment by LukasKalbertodt** [comment]
Have you seen the [`log`](https://github.com/rust-lang-nursery/log) crate? It's the de-facto standard in Rust. This crate offers convenience macros like `warn!("dfsdf {}", 45)` and relies on another crate implementing the logger. Here, usually `env_logger` is used. But you can write your own logger implementation or use another one that better suits your needs, while still being able to use the `log`-macros. 

I guess `log` together with `env_logger` is a good start.
