### ISSUE TITLE
Verify the existing learning methods

### ISSUE THREAD

**Issue by gustav1101** [vab9/pir-project2017#28]
Someone but me needs to work through this stuff and check if the code does what it is supposed to do. I got confused in the end with all the lists of vectors of slices of dvectors. Urgent.

(Note: Actual backprop not yet implemented)

**Comment by jonas-schievink** [comment]
Maybe a bit of refactoring or documenting would be appropriate here. For example, make a newtype or type alias for some confusing type you're using.

**Comment by LukasKalbertodt** [comment]
@gustav1101 @johann162 @toschneider @vab9 

I've done a quick code review of `master`. You can see all comments in [this fake PR](https://github.com/LukasKalbertodt/pir-project2017/pull/1#pullrequestreview-21065357), in case you're interested.
